name: essemu
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 4.0.3
  flutter_screenutil: 5.7.0
  shared_preferences: 2.0.18
  dio: 5.0.3
  flutter_svg: 2.0.4
  shimmer: 2.0.0
  sliding_sheet: 0.5.2
  supabase_flutter: 1.5.0
  iconly: 1.0.1
  lottie: 2.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/svg/
  uses-material-design: true

