name: essemu
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.10.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 4.0.3
  flutter_screenutil: 5.7.0
  shared_preferences: 2.0.18
  dio: 5.0.3
  flutter_svg: 2.0.4
  shimmer: 2.0.0
  sliding_sheet: 0.5.2
  supabase_flutter: 1.5.0
  iconly: 1.0.1
  lottie: 2.3.0
  connectivity: 3.0.6
  image_picker: 0.8.7
  permission_handler: 10.2.0
  geocoding: 2.1.0
  geolocator: 9.0.2
  dotted_line: 3.1.0
  animated_text_kit: 4.2.2
  badges: 3.1.1
  intl: ^0.17.0
  url_launcher: 6.1.11
  dotted_border: 2.0.0+3
  animations: 2.0.7
  flutter_keyboard_visibility: 5.4.1
  carousel_slider: 4.2.1
  fan_floating_menu: 0.0.1
  flutter_local_notifications: 15.0.0
  awesome_notifications: 0.7.4+1
  flutter_launcher_icons: 0.13.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/svg/
    - assets/lottie/
    - assets/sound/
  uses-material-design: true

